/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class AgentAgentPartnerTT (
  /* Партнер */
  partner: Option[String] = None,
  /* ГуидПартнер */
  partnerGuid: Option[String] = None,
  /* Торговая точка */
  tt: Option[String] = None,
  /* Регион закрепления */
  regionCentr: Option[String] = None,
  /* Договор */
  num: Option[String] = None,
  /* Статус */
  state: Option[String] = None,
  /* Дата договора */
  dateContract: Option[Double] = None,
  /* Дата окончания действия */
  endDate: Option[Double] = None,
  /* Гуид ТТ */
  ttGuid: Option[String] = None
) extends ApiModel


