/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Agent (
  /* ГУИД документа */
  guidDoc: Option[String] = None,
  /* Дата окончания действия */
  endDate: Option[Int] = None,
  /* ИД */
  regInfoAgentID: Option[String] = None,
  /* Табельный номер */
  regInfoTabNumber: Option[String] = None,
  /* ИНН */
  regInfoINN: Option[String] = None,
  /* СНИЛС */
  regInfoSNILS: Option[String] = None,
  /* Дата рождения */
  regInfoDateOfBirth: Option[Double] = None,
  /* Место рождения */
  regInfoPlaceOfBirth: Option[String] = None,
  /* Гражданство */
  regInfoCitizenship: Option[String] = None,
  /* Серия паспорта */
  regInfoPassSeria: Option[String] = None,
  /* Номер паспорта */
  regInfoPassNumber: Option[String] = None,
  /* Дата выдачи */
  regInfoPassIssueDate: Option[Double] = None,
  /* Кем выдан */
  regInfoPassIssuer: Option[String] = None,
  /* Телефон (дом) */
  regInfoPhoneHome: Option[String] = None,
  /* Телефон (моб) */
  regInfoPhoneMob: Option[String] = None,
  /* ЭлПочта */
  regInfoEMail: Option[String] = None,
  /* ФИО Агента */
  regInfoFullname: Option[String] = None,
  /* Фамилия */
  regInfoFIOLastname: Option[String] = None,
  /* Имя */
  regInfoFIOFirstname: Option[String] = None,
  /* Отчество */
  regInfoFIOMiddleName: Option[String] = None,
  /* Индекс */
  regAddressRAIndex: Option[String] = None,
  /* Регион */
  regAddressRARegion: Option[String] = None,
  /* Населенный пункт */
  regAddressRACity: Option[String] = None,
  /* Улица */
  regAddressRAStreet: Option[String] = None,
  /* Дом */
  regAddressRAHouse: Option[String] = None,
  /* Корпус */
  regAddressRACorp: Option[String] = None,
  /* Строение */
  regAddressRABuilding: Option[String] = None,
  /* Офис (кв.) */
  regAddressRAOffice: Option[String] = None,
  /* Полный адрес регистрации */
  regAddressRegAddress: Option[String] = None,
  /* Индекс */
  factAddressFAIndex: Option[String] = None,
  /* Регион */
  factAddressFARegion: Option[String] = None,
  /* Населенный пункт */
  factAddressFACity: Option[String] = None,
  /* Улица */
  factAddressFAStreet: Option[String] = None,
  /* Дом */
  factAddressFAHouse: Option[String] = None,
  /* Корпус */
  factAddressFACorp: Option[String] = None,
  /* Строение */
  factAddressFABuilding: Option[String] = None,
  /* Офис (кв.) */
  factAddressFAOffice: Option[String] = None,
  /* Совпадает с адресом регистрации */
  factAddressIsEqualRA: Option[Boolean] = None,
  /* Полный адрес проживания */
  factAddressFactAddress: Option[String] = None,
  /* Дивизион закрепления */
  interactionSchemeDivision: Option[String] = None,
  /* Регион закрепления */
  interactionSchemeRegionCentr: Option[String] = None,
  /* Ручная оплата */
  interactionSchemeManualPayment: Option[Boolean] = None,
  /* Ручная оплата. Комментарий */
  interactionSchemeMPComment: Option[String] = None,
  /* Представитель Банка (подписант) */
  currentSignerCSigner: Option[String] = None,
  /* Дата закрепления подписанта */
  currentSignerCSignerDate: Option[Double] = None,
  /* Действует на основании */
  currentSignerCSignerBasis: Option[String] = None,
  /* ФамилияПодписант */
  currentSignerLastnameSigner: Option[String] = None,
  /* ИмяПодписант */
  currentSignerFirstnameSigner: Option[String] = None,
  /* ОтчествоПодписант */
  currentSignerMiddleNameSigner: Option[String] = None,
  /* ГУИД подписанта */
  currentSignerGuidSigner: Option[String] = None,
  /* Закрепленный ТМ */
  currentTMCTM: Option[String] = None,
  /* Дата закрепления ТМ */
  currentTMCTMDate: Option[Double] = None,
  /* ФамилияТМ */
  currentTMLastnameTM: Option[String] = None,
  /* ИмяТМ */
  currentTMFirstnameTM: Option[String] = None,
  /* ОтчествоТМ */
  currentTMMiddleNameTM: Option[String] = None,
  /* Номер */
  currentContractCContractNum: Option[String] = None,
  /* Дата */
  currentContractCContractDate: Option[Double] = None,
  /* Статус */
  currentContractCContractState: Option[String] = None,
  /* Окончание */
  currentContractCContractEndDate: Option[Double] = None,
  /* ГУИД Договора */
  currentContractCContractGuidDoc: Option[String] = None,
  /* ФИО КАМ */
  kamfio: Option[String] = None,
  /* История статусов */
  stateHistory: Option[Seq[AgentStateHistory]] = None,
  /* История закрепления представителей Банка */
  signerHistory: Option[Seq[AgentSignerHistory]] = None,
  /* Документы (вложенные файлы) */
  agentDocs: Option[Seq[AgentAgentDocs]] = None,
  /* Сведения по ошибкам */
  errors: Option[Seq[AgentErrors]] = None,
  /* Сведения по отказам в согласовании */
  agentNonAgree: Option[Seq[AgentAgentNonAgree]] = None,
  /* Таблица Партнеры */
  agentPartnerTT: Option[Seq[AgentAgentPartnerTT]] = None,
  /* История закрепления КАМ */
  agentkamhistory: Option[Seq[AgentAgentkamhistory]] = None,
  /* Статус */
  cState: Option[String] = None,
  /* Дата назначения статуса */
  cStateDate: Option[Double] = None,
  /* ГУИД ТМ */
  tmGuidDoc: Option[String] = None,
  /* Дата Закрепления КАМ */
  kamDateKAM: Option[Double] = None,
  /* Фамилия КАМ */
  kamLastname: Option[String] = None,
  /* Имя КАМ */
  kamFirstname: Option[String] = None,
  /* Отчество КАМ */
  kamMiddleName: Option[String] = None,
  /* ГУИД КАМ */
  kamGuidDoc: Option[String] = None,
  /* История закрепления ТМ */
  tmHistory: Option[Seq[AgentTmHistory]] = None
) extends ApiModel


