/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class AgentAgentPartnerTT (
  partner: Option[String] = None,
  partnerGuid: Option[String] = None,
  tt: Option[String] = None,
  regionCentr: Option[String] = None,
  num: Option[String] = None,
  state: Option[String] = None,
  dateContract: Option[Double] = None,
  endDate: Option[Double] = None,
  ttGuid: Option[String] = None
) extends ApiModel


