/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class AgentScheme (
  /* ГУИД документа */
  guidDoc: Option[String] = None,
  /* Код услуги */
  code: Option[String] = None,
  /* Наименование услуги */
  name: Option[String] = None,
  /* null */
  versionbo: Option[Int] = None,
  /* Статус. Принимет значения  \"Черновик\", \"Закрыта\", \"Активна\" */
  state: Option[String] = None,
  /* null */
  statusDate: Option[Double] = None,
  /* Размер вознаграждений */
  rewardSheme: Option[Seq[AgentSchemeRewardSheme]] = None,
  /* Дополнительные услуги */
  rcrschemearas: Option[Seq[AgentSchemeRcrschemearas]] = None
) extends ApiModel


