/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Agent (
  guidDoc: Option[String] = None,
  state: Option[String] = None,
  stateDate: Option[Double] = None,
  partnerGUID: Option[String] = None,
  partnerName: Option[String] = None,
  partnerINN: Option[String] = None,
  partnerRegion: Option[String] = None,
  boss: Option[Boolean] = None,
  surname: Option[String] = None,
  name: Option[String] = None,
  middleName: Option[String] = None,
  fiorp: Option[String] = None,
  post: Option[String] = None,
  postRP: Option[String] = None,
  phone: Option[String] = None,
  passSeries: Option[String] = None,
  passNumber: Option[String] = None,
  issuedBy: Option[String] = None,
  issuedDate: Option[Double] = None,
  codeSubdivision: Option[String] = None,
  dateOfBirth: Option[Double] = None,
  login: Option[String] = None,
  userGUID: Option[String] = None,
  blockReason: Option[String] = None,
  blockDescription: Option[String] = None,
  blockExecutor: Option[String] = None,
  blockDate: Option[Double] = None,
  isEnablePEP: Option[Boolean] = None,
  isEnableView: Option[Boolean] = None,
  fiofull: Option[String] = None,
  address: Option[String] = None,
  surnameUpper: Option[String] = None,
  nameUpper: Option[String] = None,
  middleNameUpper: Option[String] = None,
  tradeEnterpriseSignerIsPartner: Option[String] = None,
  signerPEPDocs: Option[Seq[AgentSignerPEPDocs]] = None,
  signerPEPHistoryState: Option[Seq[AgentSignerPEPHistoryState]] = None,
  eMail: Option[String] = None,
  eMailUpper: Option[String] = None
) extends ApiModel


