/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Agent (
  guidDoc: Option[String] = None,
  endDate: Option[Int] = None,
  regInfoAgentID: Option[String] = None,
  regInfoTabNumber: Option[String] = None,
  regInfoINN: Option[String] = None,
  regInfoSNILS: Option[String] = None,
  regInfoDateOfBirth: Option[Double] = None,
  regInfoPlaceOfBirth: Option[String] = None,
  regInfoCitizenship: Option[String] = None,
  regInfoPassSeria: Option[String] = None,
  regInfoPassNumber: Option[String] = None,
  regInfoPassIssueDate: Option[Double] = None,
  regInfoPassIssuer: Option[String] = None,
  regInfoPhoneHome: Option[String] = None,
  regInfoPhoneMob: Option[String] = None,
  regInfoEMail: Option[String] = None,
  regInfoFullname: Option[String] = None,
  regInfoFIOLastname: Option[String] = None,
  regInfoFIOFirstname: Option[String] = None,
  regInfoFIOMiddleName: Option[String] = None,
  regAddressRAIndex: Option[String] = None,
  regAddressRARegion: Option[String] = None,
  regAddressRACity: Option[String] = None,
  regAddressRAStreet: Option[String] = None,
  regAddressRAHouse: Option[String] = None,
  regAddressRACorp: Option[String] = None,
  regAddressRABuilding: Option[String] = None,
  regAddressRAOffice: Option[String] = None,
  regAddressRegAddress: Option[String] = None,
  factAddressFAIndex: Option[String] = None,
  factAddressFARegion: Option[String] = None,
  factAddressFACity: Option[String] = None,
  factAddressFAStreet: Option[String] = None,
  factAddressFAHouse: Option[String] = None,
  factAddressFACorp: Option[String] = None,
  factAddressFABuilding: Option[String] = None,
  factAddressFAOffice: Option[String] = None,
  factAddressIsEqualRA: Option[Boolean] = None,
  factAddressFactAddress: Option[String] = None,
  interactionSchemeDivision: Option[String] = None,
  interactionSchemeRegionCentr: Option[String] = None,
  interactionSchemeManualPayment: Option[Boolean] = None,
  interactionSchemeMPComment: Option[String] = None,
  currentSignerCSigner: Option[String] = None,
  currentSignerCSignerDate: Option[Double] = None,
  currentSignerCSignerBasis: Option[String] = None,
  currentSignerLastnameSigner: Option[String] = None,
  currentSignerFirstnameSigner: Option[String] = None,
  currentSignerMiddleNameSigner: Option[String] = None,
  currentSignerGuidSigner: Option[String] = None,
  currentTMCTM: Option[String] = None,
  currentTMCTMDate: Option[Double] = None,
  currentTMLastnameTM: Option[String] = None,
  currentTMFirstnameTM: Option[String] = None,
  currentTMMiddleNameTM: Option[String] = None,
  currentContractCContractNum: Option[String] = None,
  currentContractCContractDate: Option[Double] = None,
  currentContractCContractState: Option[String] = None,
  currentContractCContractEndDate: Option[Double] = None,
  currentContractCContractGuidDoc: Option[String] = None,
  kamfio: Option[String] = None,
  stateHistory: Option[Seq[AgentStateHistory]] = None,
  signerHistory: Option[Seq[AgentSignerHistory]] = None,
  agentDocs: Option[Seq[AgentAgentDocs]] = None,
  errors: Option[Seq[AgentErrors]] = None,
  agentNonAgree: Option[Seq[AgentAgentNonAgree]] = None,
  agentPartnerTT: Option[Seq[AgentAgentPartnerTT]] = None,
  agentkamhistory: Option[Seq[AgentAgentkamhistory]] = None,
  cState: Option[String] = None,
  cStateDate: Option[Double] = None,
  tmGuidDoc: Option[String] = None,
  kamDateKAM: Option[Double] = None,
  kamLastname: Option[String] = None,
  kamFirstname: Option[String] = None,
  kamMiddleName: Option[String] = None,
  kamGuidDoc: Option[String] = None,
  tmHistory: Option[Seq[AgentTmHistory]] = None
) extends ApiModel


