/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class CommonLogicSchema (
  ge: Option[LeftRightCLSchema] = None,
  gt: Option[LeftRightCLSchema] = None,
  le: Option[LeftRightCLSchema] = None,
  lt: Option[LeftRightCLSchema] = None,
  `object`: Option[FieldCLSchema] = None,
  left: Option[ValueCLSchema] = None,
  right: Option[ValueCLSchema] = None,
  like: Option[LeftRightCLSchema] = None,
  ilike: Option[LeftRightCLSchema] = None,
  and: Option[NestedConditionCLSchema] = None,
  eq: Option[LeftRightCLSchema] = None,
  or: Option[NestedConditionCLSchema] = None
) extends ApiModel


