/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class CommonLogic (
  eq: Option[EqCLSchema] = None,
  ge: Option[GeCLSchema] = None,
  gt: Option[GtCLSchema] = None,
  le: Option[LeCLSchema] = None,
  lt: Option[LtCLSchema] = None,
  between: Option[BetweenCLSchema] = None,
  like: Option[LikeCLSchema] = None,
  ilike: Option[ILikeCLSchema] = None,
  and: Option[AndCLSchema] = None,
  or: Option[OrCLSchema] = None,
  not: Option[NotCLSchema] = None
) extends ApiModel


