/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ContractPartiesAgreed (
  /* Отображаемое значение */
  name: Option[String] = None,
  /* Техническое поле */
  enumType: Option[String] = None,
  /* Отображаемое значение */
  description: Option[String] = None,
  /* lit1 - дополнить Договор Приложением № 2 и изложить его в редакции Приложения № 1 к настоящему Дополнительному соглашению, lit2 - изменить Приложение № 2 к Договору и изложить его в редакции Приложения № 1 к настоящему Дополнительному соглашению. Возможные значения: \"lit1\", \"lit2\" */
  value: Option[String] = None
) extends ApiModel


