/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ContractDocType (
  content: Option[String] = None,
  code: Option[String] = None,
  /* New- Новый, OnReplace - На замену */
  value: Option[ContractDocTypeEnums.Value] = None
) extends ApiModel

object ContractDocTypeEnums {

  type Value = Value.Value
  object Value extends Enumeration {
    val `New` = Value("New")
    val OnReplace = Value("OnReplace")
  }

}

