/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ContractPartnerSchemeRCRContractBR (
  /* ГВ Нижняя граница */
  brBorderDown: Option[Double] = None,
  /* ГВ Верхняя граница */
  brBorderUpper: Option[Double] = None,
  /* ГВ Флаг ограничений */
  brBorderNon: Option[Boolean] = None,
  /* Вознаграждение по продуктам для границ вознаграждений */
  rcrContractBRL: Option[Seq[ContractRcrContractBRL]] = None
) extends ApiModel


