/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ContractRcrContractBRL (
  /* ФПН */
  brlfpn: Option[String] = None,
  /* ПВС ГУИД КП */
  brlGuidDoc: Option[String] = None,
  /* ПВС Код продукта */
  brlCode: Option[String] = None,
  /* ПВС Наименование КП */
  brlNameKP: Option[String] = None,
  /* ПВС Без страховки */
  brlOutInsurance: Option[Double] = None,
  /* ПВС Страховка 1 */
  brlInsurance1: Option[Double] = None,
  /* ПВС Страховка 2 */
  brlInsurance2: Option[Double] = None,
  /* ПВС Возможный срок, мес.: от */
  brlLoanTermMin: Option[Int] = None,
  /* ПВС Возможный срок, мес.: до */
  brlLoanTermMax: Option[Int] = None,
  /* ПВС Первоначальный взнос */
  brlDownPayments: Option[String] = None,
  /* ПВС Минимальная сумма кредита, руб. */
  brlLimitMin: Option[Double] = None,
  /* ПВС Максимальная сумма кредита, руб. */
  brlLimitMax: Option[Double] = None
) extends ApiModel


