/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Contract (
  /* По форме */
  basicDocName: Option[String] = None,
  basicDoc: Option[ContractBasicDoc] = None,
  subject: Option[ContractSubject] = None,
  /* ГУИД документа */
  guidDoc: Option[String] = None,
  basicDocDop: Option[ContractBasicDocDop] = None,
  /* Наименование */
  name: Option[String] = None,
  docType: Option[ContractDocType] = None,
  /* Исходный документ № */
  modifyDoc: Option[String] = None,
  /* ГУИД исходного документа */
  guidModifyDoc: Option[String] = None,
  /* Назначение документа */
  docPurpose: Option[String] = None,
  /* От */
  dateInitialDoc: Option[Double] = None,
  forCheck: Option[String] = None,
  /* Гуид Агента */
  guidAgent: Option[String] = None,
  /* ГУИД ДС */
  guidDS: Option[String] = None,
  /* Для НК */
  forNk: Option[String] = None,
  /* ГУИД Договора */
  guidContract: Option[String] = None,
  partiesAgreed: Option[ContractPartiesAgreed] = None,
  /* Число месяца начала отчетного периода */
  startDate: Option[Int] = None,
  /* Длительность отчетного периода, мес. */
  period: Option[Int] = None,
  /* Дата начала последнего отчетного периода */
  beginDateAndFillField: Option[String] = None,
  /* Телефон */
  phone: Option[String] = None,
  partnerType: Option[ContractPartnerType] = None,
  /* Регион юридического адреса */
  regionLegalAddress: Option[String] = None,
  ispep: Option[ContractIspep] = None,
  /* Эскалирование */
  isescalate: Option[Boolean] = None,
  /* ГУИД вложения с пдф-файлом для банка 1  */
  guidpdfbankhash: Option[String] = None,
  /* ГУИД вложения с пдф-файлом для банка 2 */
  guidpdfbanksign: Option[String] = None,
  /* ГУИД вложения с пдф-файлом для партнера 1  */
  guidpdfpartnerhash: Option[String] = None,
  /* ГУИД вложения с пдф-файлом для партнера 2 */
  guidpdfpartnersign: Option[String] = None,
  /* Хэш1 */
  hashbank: Option[String] = None,
  /* Хэш2 */
  hashpartner: Option[String] = None,
  /* Логин сотрудника банка */
  loginbanksign: Option[String] = None,
  /* Дата и время подписи банка */
  datebanksign: Option[Double] = None,
  /* СМС код для банка */
  smsbank: Option[String] = None,
  /* Дата и время доставки смсКода сотруднику банка */
  smsbankdate: Option[Double] = None,
  /* Телефон сотрудника банка */
  telefonbank: Option[String] = None,
  /* Логин партнера */
  loginpartnersign: Option[String] = None,
  /* Дата и время подписи партнера */
  datepartnersign: Option[Double] = None,
  /* СМС код для партнера */
  smspartner: Option[String] = None,
  /* Дата и время доставки смсКода партнеру */
  smspartnerdate: Option[Double] = None,
  /* Телефон партнера */
  telefonpartner: Option[String] = None,
  /* Документ подписан сотрудником банка */
  isbanksign: Option[Boolean] = None,
  /* Документ подписан партнером */
  ispartnersign: Option[Boolean] = None,
  /* Гуид доверенности сотрудника банка */
  guidpowerattorneybank: Option[String] = None,
  /* ГУИД подписанта сотрудника банка */
  guidsignerbank: Option[String] = None,
  /* Гуид доверенности сотрудника партнера */
  guidpowerattorneypartner: Option[String] = None,
  /* Гуид сотрудника партнера подписанта партнера */
  guidsignerpartner: Option[String] = None,
  /* Гуид вложения с отчетом банка */
  guidreportbank: Option[String] = None,
  /* Гуид вложения с отчетом партнера */
  guidreportpartner: Option[String] = None,
  howFillDate: Option[ContractHowFillDate] = None,
  /* Номер */
  regInfoNum: Option[String] = None,
  /* Дата договора */
  regInfoDateDoc: Option[Double] = None,
  /* Договор */
  regInfoContractNum: Option[String] = None,
  /* Дата окончания действия */
  regInfoEndDate: Option[Double] = None,
  regInfoTTMode: Option[ContractRegInfoTTMode] = None,
  /* Дополнительное соглашение № */
  regInfoAddAgreement: Option[String] = None,
  /* На дату Дата доп соглашения */
  regInfoForDate: Option[Double] = None,
  /* Дата расторжения договора */
  regInfoDateCancelCon: Option[Double] = None,
  /* Дата отправки в архив */
  originalsInfoSentArchive: Option[Double] = None,
  /* Наименование */
  tradeEnterprisePartner: Option[String] = None,
  /* Ссылка на карточку партнера агента */
  tradeEnterpriseReferenceCard: Option[String] = None,
  /* Вышестоящий партнер */
  tradeEnterpriseParentPartner: Option[String] = None,
  /* Вышестоящий партнер ГУИД документа */
  tradeEnterpriseParentPartnerGuid: Option[String] = None,
  /* ФИО представителя */
  tradeEnterpriseNameRepresent: Option[String] = None,
  /* ФИО представителя р.п. */
  tradeEnterpriseNameRepresentRP: Option[String] = None,
  /* Представитель партнера. Должность и.п. */
  tradeEnterprisePostRepresent: Option[String] = None,
  /* Представитель партнера. Должность р.п. */
  tradeEnterprisePostRepresentRP: Option[String] = None,
  /* Основание полномочий */
  tradeEnterpriseBasisPowers: Option[String] = None,
  /* Юридический адрес */
  tradeEnterpriseLegalAddress: Option[String] = None,
  /* Фактический адрес */
  tradeEnterpriseActualAddress: Option[String] = None,
  /* Телефон */
  tradeEnterprisePhone: Option[String] = None,
  /* Факс */
  tradeEnterpriseFax: Option[String] = None,
  /* Расчетный счет */
  tradeEnterpriseSettlemAccount: Option[String] = None,
  /* Наименование банка */
  tradeEnterpriseBankName: Option[String] = None,
  /* ИНН партнера (не банка) */
  tradeEnterpriseINN: Option[String] = None,
  /* КПП партнера */
  tradeEnterpriseKPP: Option[String] = None,
  /* БИК банка в котором обслуживается партнер */
  tradeEnterpriseBIK: Option[String] = None,
  /* Корреспондентский счет */
  tradeEnterpriseCorrespAccount: Option[String] = None,
  /* ОКПО партнера */
  tradeEnterpriseOKPO: Option[String] = None,
  /* Регион */
  tradeEnterpriseRegion: Option[String] = None,
  /* Дивизион */
  tradeEnterpriseDivision: Option[String] = None,
  /* Схема налогообложения */
  tradeEnterpriseTaxScheme: Option[String] = None,
  /* ФИО руководителя */
  tradeEnterpriseULChiefFIO: Option[String] = None,
  /* ЭлПочта */
  tradeEnterpriseEMail: Option[String] = None,
  /* Форма регистрации */
  tradeEnterpriseRegForm: Option[String] = None,
  /* ОГРН */
  tradeEnterpriseOGRN: Option[String] = None,
  /* Серия паспорта */
  tradeEnterprisePassSeria: Option[String] = None,
  /* Номер паспорта */
  tradeEnterprisePassNumber: Option[String] = None,
  /* Дата выдачи */
  tradeEnterprisePassIssueDate: Option[Double] = None,
  /* Кем выдан */
  tradeEnterprisePassIssuer: Option[String] = None,
  /* Код подразделения */
  tradeEnterpriseCodeSubdivision: Option[String] = None,
  /* Подписант совпадает с партнером */
  tradeEnterpriseSignerIsPartner: Option[String] = None,
  /* ФИО Кконсультанта */
  infoConsultantAgent: Option[String] = None,
  /* Адрес проживания */
  infoConsultantResidentAddress: Option[String] = None,
  /* Адрес регистрации */
  infoConsultantRegisAddress: Option[String] = None,
  /* Регион */
  infoConsultantRegion: Option[String] = None,
  /* Серия паспорта */
  consultRequisitPassSeria: Option[String] = None,
  /* Номер паспорта */
  consultRequisitPassNumber: Option[String] = None,
  /* Дата выдачи */
  consultRequisitPassIssueDate: Option[Double] = None,
  /* Кем выдан */
  consultRequisitPassIssuer: Option[String] = None,
  /* Когда выдан */
  consultRequisitGivenOut: Option[Double] = None,
  /* СНИЛС № */
  consultRequisitNumPensionFund: Option[String] = None,
  /* ЭлПочта */
  consultRequisitEMail: Option[String] = None,
  /* Дата рождения */
  consultRequisitDateOfBirth: Option[Double] = None,
  /* Представитель банка */
  dataOnBankBankRepresent: Option[String] = None,
  /* ФИО представителя (родительный падеж) */
  dataOnBankNameRepresent: Option[String] = None,
  /* Должность (родительный падеж) */
  dataOnBankPosition: Option[String] = None,
  /* Основание полномочий (родительный падеж) */
  dataOnBankBasisPowers: Option[String] = None,
  /* Адрес банка */
  dataOnBankBankAddress: Option[String] = None,
  /* Должность */
  dataOnBankPostInIP: Option[String] = None,
  /* Телефон */
  dataOnBankBankPhone: Option[String] = None,
  /* ГУИД Представителя банка */
  dataOnBankGuid: Option[String] = None,
  /* Наименование банка */
  bankDetailsBankName: Option[String] = None,
  /* Где обслуживается кс */
  bankDetailsServed: Option[String] = None,
  /* Где обслуживается к/с (р. п.) - сокращенно */
  bankDetailsServedShort: Option[String] = None,
  /* Корреспондентский счет */
  bankDetailsCorrespAccount: Option[String] = None,
  /* ИНН */
  bankDetailsINN: Option[String] = None,
  /* КПП */
  bankDetailsKPP: Option[String] = None,
  /* БИК */
  bankDetailsBIK: Option[String] = None,
  /* СВ Начало отчетного периода */
  schemesRemunSRPeriodOn: Option[Int] = None,
  /* СВ Окончание отчетного периода */
  schemesRemunSRPeriodOff: Option[Int] = None,
  /* СВ Длительность отчетного периода */
  schemesRemunSRPeriodRange: Option[Int] = None,
  schemesRemunSRAmountSP: Option[Double] = None,
  /* ПС ГУИД схемы */
  partnerSchemePSGuid: Option[String] = None,
  /* ПС Наименование схемы */
  partnerSchemePSScheme: Option[String] = None,
  partnerSchemePSVersionBO: Option[Int] = None,
  /* ПС Алгорим расчета Наименование */
  partnerSchemePSACName: Option[String] = None,
  /* ПС Алгорим расчета Код */
  partnerSchemePSACCode: Option[Int] = None,
  /* ПС Дата подключения */
  partnerSchemePSDateOn: Option[Double] = None,
  /* ПС Дата отключения */
  partnerSchemePSDateOff: Option[Double] = None,
  /* ПС Учитывать НДС */
  partnerSchemePSFlagNDS: Option[Boolean] = None,
  /* ПС Учитывать страховку */
  partnerSchemePSFlagInsurance: Option[Boolean] = None,
  /* ПС Гарантированное вознаграждение */
  partnerSchemePSGuaranAmount: Option[Double] = None,
  partnerSchemePSStateLine: Option[String] = None,
  /* Гуид схемы КВ для отключения */
  partnerSchemePSGuidDisable: Option[String] = None,
  /* АС Наименование схемы */
  agentSchemeASNameScheme: Option[String] = None,
  /* АС Ссылка (ГУИД) на агентскую схему вознаграждения */
  agentSchemeASReferenAgency: Option[String] = None,
  /* Документы  */
  contractDocs: Option[Seq[AgentAgentDocs]] = None,
  /* Торговые точки */
  outlets: Option[Seq[ContractOutlets]] = None,
  /* Кредитные продукты */
  creditProduct: Option[Seq[ContractCreditProduct]] = None,
  /* История статусов */
  conStateHistory: Option[Seq[AgentStateHistory]] = None,
  /* Сведения по ошибкам */
  contractErrors: Option[Seq[ContractContractErrors]] = None,
  /* Сведения по отказам в согласовании */
  contractNonAgree: Option[Seq[ContractContractNonAgree]] = None,
  /* Проценты вознаграждений */
  partnerSchemeRCRContractIR: Option[Seq[ContractPartnerSchemeRCRContractIR]] = None,
  /* Границы вознаграждения */
  partnerSchemeRCRContractBR: Option[Seq[ContractPartnerSchemeRCRContractBR]] = None,
  /* Границы вознаграждений дополнительное вознаграждение */
  partnerSchemeRCRContractBRD: Option[Seq[ContractPartnerSchemeRCRContractBRD]] = None,
  /* Категории ТТ */
  partnerSchemeRCRContractTT: Option[Seq[ContractPartnerSchemeRCRContractTT]] = None,
  /* Проценты вознаграждений по агентской схеме */
  agentSchemeRCRContractT13: Option[Seq[ContractAgentSchemeRCRContractT13]] = None,
  /* Статус */
  cState: Option[String] = None,
  /* Дата назначения статуса */
  cStateDate: Option[Double] = None,
  tmguidDoc: Option[String] = None,
  /* Инн Агента */
  innAgent: Option[String] = None,
  conline: Option[Boolean] = None,
  coffline: Option[Boolean] = None,
  /* Дополнительные услуги */
  rcrContractAS: Option[Seq[ContractRcrContractAS]] = None
) extends ApiModel


