/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ContractPartnerSchemeRCRContractIR (
  /* ФПН */
  irfpn: Option[String] = None,
  /* ПВ ГУИД КП */
  irGuidDoc: Option[String] = None,
  /* ПВ Код продукта */
  irCode: Option[String] = None,
  /* ПВ Группа продуктов */
  irNameKP: Option[String] = None,
  /* ПВ Без страховки */
  irOutInsurance: Option[Double] = None,
  /* ПВ Страховка 1 */
  irInsurance1: Option[Double] = None,
  /* ПВ Страховка 2 */
  irInsurance2: Option[Double] = None,
  /* ПВ Возможный срок, мес.: от */
  irLoanTermMin: Option[Int] = None,
  /* ПВ Возможный срок, мес.: до */
  irLoanTermMax: Option[Int] = None,
  /* ПВ Первоначальный взнос */
  irDownPayments: Option[String] = None,
  /* ПВ Минимальная сумма кредита, руб. */
  irLimitMin: Option[Double] = None,
  /* ПВ Максимальная сумма кредита, руб. */
  irLimitMax: Option[Double] = None
) extends ApiModel


