/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ContractOutlets (
  /* ГУИД экземпляра формуляра торговой точки */
  guidTT: Option[String] = None,
  /* Наименование */
  name: Option[String] = None,
  /* Код ТТ */
  code: Option[String] = None,
  /* Адрес режим работы */
  address: Option[String] = None,
  /* Адрес электронной почты телефон */
  email: Option[String] = None,
  /* Телефон */
  phone: Option[String] = None,
  /* Уполномоченное лицо */
  authorPerson: Option[String] = None,
  /* Представитель партнера (подписант) */
  partnerRepresent: Option[String] = None,
  ttMode: Option[ContractTtMode] = None
) extends ApiModel


