/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ContractBasicDocDop (
  content: Option[String] = None,
  code: Option[String] = None,
  /* actAward - акт по вознаграждению, contract - договор, additionalAgreement - дополнительное соглашение, contractPEP - Соглашение о ПЭП */
  value: Option[ContractBasicDocDopEnums.Value] = None
) extends ApiModel

object ContractBasicDocDopEnums {

  type Value = Value.Value
  object Value extends Enumeration {
    val ActAward = Value("actAward")
    val Contract = Value("contract")
    val AdditionalAgreement = Value("additionalAgreement")
    val ContractPEP = Value("contractPEP")
  }

}

