/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class EmployeeAuthority (
  /* ГУИД документа */
  guidDoc: Option[String] = None,
  /* ГУИД карточки подписанта */
  signerPepGUID: Option[String] = None,
  /* Статус */
  state: Option[String] = None,
  /* Дата назначения статуса */
  stateDate: Option[Double] = None,
  /* Гуид партнера */
  partnerGUID: Option[String] = None,
  /* Название партнера */
  partnerName: Option[String] = None,
  /* Партнер ИНН */
  partnerINN: Option[String] = None,
  /* Регион закрепления партнера */
  partnerRegion: Option[String] = None,
  /* Фамилия */
  surname: Option[String] = None,
  /* Имя */
  name: Option[String] = None,
  /* Отчество */
  middleName: Option[String] = None,
  /* Должность */
  post: Option[String] = None,
  /* Логин подписанта ПЭП */
  login: Option[String] = None,
  /* Для просмотра */
  forView: Option[Boolean] = None,
  /* Для подписи ПЭП */
  forSign: Option[Boolean] = None,
  /* Дата начала полномочий */
  dateOn: Option[Double] = None,
  /* Дата окончания полномочий */
  dateOff: Option[Double] = None,
  /* Руководитель */
  boss: Option[Boolean] = None,
  /* Бессрочные полномочия */
  notLimit: Option[Boolean] = None,
  /* Причина отзыва */
  reason: Option[String] = None,
  /* Основание полномочий (родительный падеж) */
  basisPowers: Option[String] = None,
  /* ДолжностьВрп */
  postrp: Option[String] = None,
  /* ФИО в РП */
  fiorp: Option[String] = None,
  /* Дата доверенности прописью */
  datePowerAsText: Option[String] = None,
  /* Подписант совпадает с партнером */
  tradeEnterpriseSignerIsPartner: Option[String] = None,
  /* Серия паспорта */
  passportPASSSERIES: Option[String] = None,
  /* Номер паспорта */
  passportPASSNUMBER: Option[String] = None,
  /* Кем выдан */
  passportISSUEWHOME: Option[String] = None,
  /* Дата выдачи */
  passportISSUEDATE: Option[Double] = None,
  /* Код подразделения */
  passportDIVISIONCODE: Option[String] = None,
  /* Дата рождения */
  passportDATEOFBIRTH: Option[Double] = None,
  /* Номер доверенности */
  paNum: Option[String] = None,
  /* Дата доверенности */
  paDateOn: Option[Double] = None,
  /* Дата окончания действия */
  paDateOff: Option[Double] = None,
  /* Файл с доверенностью */
  paFile: Option[String] = None,
  /* ФИО полное */
  fioFull: Option[String] = None
) extends ApiModel


