/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class LoanProduct (
  name: Option[String] = None,
  fpn: Option[String] = None,
  code: Option[String] = None,
  groupProduct: Option[LoanProductGroupProduct] = None,
  apr: Option[String] = None,
  loanTermMin: Option[Int] = None,
  loanTermMax: Option[Int] = None,
  downPayments: Option[String] = None,
  discount: Option[Double] = None,
  irr: Option[Double] = None,
  limitMin: Option[Double] = None,
  limitMax: Option[Double] = None,
  productGroup: Option[String] = None,
  guidDoc: Option[String] = None,
  isAgreement: Option[Boolean] = None,
  agreementRole: Option[LoanProductAgreementRole] = None,
  state: Option[String] = None
) extends ApiModel


