/**
 * rest сервисы УФОС
 * rest сервисы ядра УФОС
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class OrderElement2 (
  /* наименование поля для сортировки. Обязательный параметр */
  fieldName: String,
  /* направление сортировки по возрастанию. По умолчанию true */
  ascending: Option[Boolean] = None
) extends ApiModel


