/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class PartnerListHistoryState (
  /* ИС Статус */
  hsState: Option[String] = None,
  /* ИС Дата назначения статуса */
  hsStateDate: Option[Double] = None,
  /* ИС Продолжительность работ, дн. */
  hsDuration: Option[Int] = None,
  /* ИС Исполнитель */
  hsExecutorFIO: Option[String] = None,
  /* ИС Роль исполнителя */
  hsExecutorRole: Option[String] = None
) extends ApiModel


