/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class PartnerServicesRange (
  /* Дата начала действия */
  dateOn: Option[Double] = None,
  /* Дата начала действия (по умолчанию) */
  dateOnDefault: Option[Double] = None,
  /* Размер вознаграждения */
  rewardOne: Option[Double] = None,
  /* Размер вознаграждения (по умолчанию) */
  rewardOneDefault: Option[Double] = None,
  unit: Option[PartnerUnit] = None
) extends ApiModel


