/**
 * rest сервисы ренессанс
 * rest сервисы ренессансsdsdd
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class PartnerAdditionalRewardScope (
  /* ГВД Нижняя граница */
  brdBorderDown: Option[Double] = None,
  /* ГВД Верхняя граница */
  brdBorderUpper: Option[Double] = None,
  /* ГВД Флаг ограничений */
  brdBorderNon: Option[Boolean] = None,
  /* ГВД Процент вознаграждения */
  brdPercentRewards: Option[Double] = None
) extends ApiModel


