/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class PartnerListRejects (
  /* Статус */
  applState: Option[String] = None,
  /* Описание решения */
  applNote: Option[String] = None,
  /* Автор */
  applAuthor: Option[String] = None,
  /* Дата */
  applDate: Option[Double] = None,
  /* Флаг удаления */
  applDelFlag: Option[String] = None
) extends ApiModel


