/**
 * rest сервисы ренессанс
 * rest сервисы ренессансsdsdd
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class PartnerEmployeeSignerPEPHistoryState (
  state: Option[String] = None,
  stateDate: Option[Double] = None,
  duration: Option[Int] = None,
  executorFIO: Option[String] = None
) extends ApiModel


