/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class PartnerListAttachedAggents (
  /* ПАТабельный номер */
  agentTabelNum: Option[String] = None,
  /* ПАФИО */
  agentFIO: Option[String] = None,
  /* ПА ИД */
  agentID: Option[String] = None,
  /* ПА Дата начала сотрудничества  */
  agentDateStart: Option[Double] = None,
  /* ПА Дивизион */
  agentDivision: Option[String] = None,
  /* ПА Регион */
  agentRegion: Option[String] = None,
  /* ПА Агентская схема */
  agentShema: Option[String] = None,
  /* ПА Адрес */
  agentAddress: Option[String] = None,
  /* ПАТелефон */
  agentPhone: Option[String] = None
) extends ApiModel


