/**
 * rest сервисы ренессанс
 * rest сервисы ренессансsdsdd
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class PartnerListFiles (
  /* ПФ Файл */
  adattachlink: Option[String] = None,
  /* ссылка на вложение */
  attachlink: Option[String] = None,
  /* МимеТип */
  mimetype: Option[String] = None,
  /* ПФ Запретить изменения */
  adNotChenge: Option[Boolean] = None,
  /* Флаг удаления */
  adDelFlag: Option[String] = None,
  /* ПФ Тип документа */
  adDocType: Option[String] = None,
  /* ПФ Описание */
  adDescript: Option[String] = None,
  /* ПФ Признак актуальности */
  adIsActive: Option[Boolean] = None,
  /* ПФ Комментарии */
  adComment: Option[String] = None,
  /* ПФ Дата представления */
  adDateCreate: Option[Double] = None
) extends ApiModel


