/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class PartnerPartnerkamhistory (
  /* ФИО КАМ */
  kamfio: Option[String] = None,
  /* Автор изменения */
  authorChanges: Option[String] = None,
  /* Дата изменения */
  dateChanges: Option[Double] = None,
  /* Гуид записи из справочника Пользователи */
  guidfixedkam: Option[String] = None,
  /* Дата открепления */
  dateoff: Option[Double] = None,
  /* Тип сотрудника */
  typeempl: Option[String] = None,
  /* Дата закрепления КАМ */
  kamDate: Option[Double] = None
) extends ApiModel


