/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class RewardRewDocSum (
  /* Значение */
  value: Option[Double] = None,
  /* Гуид типа суммы */
  guidSumType: Option[String] = None,
  /* Наименование */
  name: Option[String] = None,
  /* НаименованиеРус */
  nameRus: Option[String] = None,
  /* Значение прописью */
  valueWords: Option[String] = None,
  /* Код типа суммы */
  dsCode: Option[String] = None
) extends ApiModel


