/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Reward (
  /* Предельное время обработки  */
  kpi: Option[Int] = None,
  /* Регион закрепления */
  region: Option[String] = None,
  /* Дивизион */
  division: Option[String] = None,
  /* Номер акта */
  actNumber: Option[String] = None,
  /* ПодписанПЭП */
  signWithPep: Option[Boolean] = None,
  /* Дата создания договора */
  contractCreatationDate: Option[Double] = None,
  /* Имя файла */
  fileName: Option[String] = None,
  /* Учитывать повышающий коэффициент */
  svflaginsurance: Option[Boolean] = None,
  /* Общая сумма */
  totalAmount: Option[Double] = None,
  /* Согласован ПЭП сотрудника банка */
  signWithPepWorker: Option[Boolean] = None,
  partnerType: Option[ContractPartnerType] = None,
  /* ГУИД вложения с пдф-файлом для банка 1  */
  guidpdfbankhash: Option[String] = None,
  /* ГУИД вложения с пдф-файлом для банка 2 */
  guidpdfbanksign: Option[String] = None,
  /* ГУИД вложения с пдф-файлом для партнера 1  */
  guidpdfpartnerhash: Option[String] = None,
  /* ГУИД вложения с пдф-файлом для партнера 2 */
  guidpdfpartnersign: Option[String] = None,
  /* Хэш1 */
  hashbank: Option[String] = None,
  /* Хэш2 */
  hashpartner: Option[String] = None,
  /* СМС код для банка */
  smsbank: Option[String] = None,
  /* Дата и время доставки смсКода сотруднику банка */
  smsbankdate: Option[Double] = None,
  /* Телефон сотрудника банка */
  telefonbank: Option[String] = None,
  /* Логин партнера */
  loginpartnersign: Option[String] = None,
  /* СМС код для партнера */
  smspartner: Option[String] = None,
  /* Дата и время доставки смсКода партнеру */
  smspartnerdate: Option[Double] = None,
  /* Телефон партнера */
  telefonpartner: Option[String] = None,
  /* Гуид доверенности сотрудника банка */
  guidpowerattorneybank: Option[String] = None,
  /* ГУИД подписанта сотрудника банка */
  guidsignerbank: Option[String] = None,
  /* Гуид доверенности сотрудника партнера */
  guidpowerattorneypartner: Option[String] = None,
  /* Логин сотрудника банка */
  loginbanksign: Option[String] = None,
  /* Гуид сотрудника партнера подписанта партнера */
  guidsignerpartner: Option[String] = None,
  /* Гуид вложения с отчетом банка */
  guidreportbank: Option[String] = None,
  /* Гуид вложения с отчетом партнера */
  guidreportpartner: Option[String] = None,
  /* Статус */
  basicInfoCState: Option[String] = None,
  /* Дата назначения статуса */
  basicInfoCStateDate: Option[Double] = None,
  basicInfoPDSubject: Option[RewardBasicInfoPDSubject] = None,
  /* Ссылка на карточку агента или партнера */
  basicInfoPDContractorGUID: Option[String] = None,
  /* ИНН партнера */
  basicInfoPDPartnerINN: Option[String] = None,
  /* Идентификатор агента */
  basicInfoPDAgentID: Option[String] = None,
  /* Предприятие торговли /Консультант */
  basicInfoPDContractorName: Option[String] = None,
  /* Дата акта */
  basicInfoPDDocDate: Option[Double] = None,
  /* Отчетный период начало */
  basicInfoPDDateStart: Option[Double] = None,
  /* Отчетный период окончание */
  basicInfoPDDateEnd: Option[Double] = None,
  /* Типовой расчета */
  basicInfoPDIsAutomatic: Option[Boolean] = None,
  /* Код алгоритма вознаграждения партнера */
  basicInfoPDCodeSchemeKV: Option[Int] = None,
  /* Код агентской схемы вознаграждения */
  basicInfoPDCodeAgentScheme: Option[String] = None,
  /* Алгоритм расчета */
  basicInfoPDAlgoritm: Option[String] = None,
  /* Форма акта */
  basicInfoPDBasicDocName: Option[String] = None,
  /* Признак группировки кредитов по категориям ТТ */
  basicInfoPDIsTTGroup: Option[Boolean] = None,
  /* Гуид схемы КВ партнера */
  basicInfoPDGuidScheme: Option[String] = None,
  /* Использовать нетиповую форму акта */
  basicInfoPDIsNonBasicForm: Option[Boolean] = None,
  /* Форма Акта  */
  basicInfoPDFormAct: Option[String] = None,
  /* Форма регистрации */
  basicInfoPDRegForm: Option[String] = None,
  /* ОГРН */
  basicInfoPDOGRN: Option[String] = None,
  /* Подписант совпадает с партнером */
  basicInfoPDSignerIsPartner: Option[String] = None,
  /* Лицо от Банка, подтвердившее Акт */
  signinInfoBankSign: Option[String] = None,
  /* Дата подтверждения Акта Банком */
  signinInfoBankDate: Option[Double] = None,
  /* Партнер/Агент, подтвердивший Акт */
  signinInfoContractorSign: Option[String] = None,
  /* Дата подтверждения Акта Партнером/Агентом */
  signinInfoContractorDate: Option[Double] = None,
  /* Лицо от Банка, подтвердившее Акт в р.п. */
  signinInfoCONFIRMER: Option[String] = None,
  /* На основании */
  signinInfoFOUNDATION: Option[String] = None,
  /* Регион */
  signinInfoRegionContract: Option[String] = None,
  /* Наименование банка */
  signinInfoBankName: Option[String] = None,
  /* Адрес банка */
  signinInfoBankAddress: Option[String] = None,
  /* Основание полномочий (родительный падеж) */
  signinInfoBasisPowers: Option[String] = None,
  /* Представитель партнера. Должность р.п. */
  signinInfoPostRepresentRP: Option[String] = None,
  /* ФИО представителя р.п. */
  signinInfoNameRepresentRP: Option[String] = None,
  /* Юридический адрес */
  signinInfoLegalAddress: Option[String] = None,
  /* ФИО представителя */
  signinInfoNameRepresent: Option[String] = None,
  /* Номер доверенности сотрудника банка */
  signinInfoPANUM: Option[String] = None,
  /* Дата доверенности */
  signinInfoPADATEON: Option[Double] = None,
  /* ФИО представителя банка в рп */
  signinInfoBankFIORP: Option[String] = None,
  /* Должность представителя банка в ип */
  signinInfoBankPost: Option[String] = None,
  /* Должность представителя банка в рп */
  signinInfoBankPostRP: Option[String] = None,
  /* ФИО руководителя ИП */
  signinInfoIPChiefFIO: Option[String] = None,
  /* Гуид ДС */
  addAgreementPrtnGUID: Option[String] = None,
  /* ДС номер */
  addAgreementPrtnNum: Option[String] = None,
  /* От дата ДС */
  addAgreementPrtnDateDS: Option[Double] = None,
  /* Форма ДС */
  addAgreementPrtnBaseDoc: Option[String] = None,
  /* Схема налогообложения */
  addAgreementPrtnTaxScheme: Option[String] = None,
  /* Гуид договора  */
  contractAgentGUID: Option[String] = None,
  /* Договор номер */
  contractAgentNum: Option[String] = None,
  /* Дата */
  contractAgentDateD: Option[Double] = None,
  /* К договору номер  */
  contractPartnerNum: Option[String] = None,
  /* от дата договора */
  contractPartnerPCDate: Option[Double] = None,
  techPanelRoleNoAccess: Option[String] = None,
  /* История статусов */
  rewStateHistory: Option[Seq[AgentStateHistory]] = None,
  /* Итоговые суммы документа */
  rewDocSum: Option[Seq[RewardRewDocSum]] = None,
  /* Категории торговых точек */
  rewCategorOutlets: Option[Seq[RewardRewCategorOutlets]] = None,
  /* Сведения по ошибкам */
  rewErrorInfo: Option[Seq[RewardRewErrorInfo]] = None,
  /* Сведения по отказам в согласовании */
  rewAgreeInfo: Option[Seq[AgentAgentNonAgree]] = None,
  /* Документы (вложенные файлы) */
  rewAgentDocs: Option[Seq[RewardRewAgentDocs]] = None,
  /* Предельная дата обработки */
  cLimitDate: Option[Double] = None
) extends ApiModel


