/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class RewardGroupSumAS (
  /* Цена одной услуги */
  maxADDSRate: Option[Double] = None,
  /* Сумма вознаграждения за продажу одинаковых дополнительных услуг */
  sumADDSRewardOne: Option[Double] = None,
  /* Количество проданных одинаковых дополнительных услуг */
  sumADDSAmount: Option[Int] = None,
  /* Наименование дополнительной услуги */
  addsName: Option[String] = None
) extends ApiModel


