/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class RewardCreditsAggrReq (
  /* Фпн продукта */
  productFPN: Option[String] = None,
  /* Продукт */
  product: Option[String] = None,
  /* Общая сумма */
  sumTotalAmount: Option[Double] = None,
  /* Сумма на товар 00 */
  sumGoodsAmountGr0: Option[Double] = None,
  /* Вознаграждение баз 00 */
  maxRewardPercentGr0: Option[Double] = None,
  /* Сумма на товар 0 */
  sumGoodsAmountEq0: Option[Double] = None,
  /* Вознаграждение баз 0 */
  maxRewardPercentEq0: Option[Double] = None,
  /* Сумма вознаграждения */
  sumTotalRewardAmount: Option[Double] = None,
  /* Сумма на товар */
  sumGoodsAmount: Option[Double] = None,
  /* Вознаграждение баз */
  maxRewardPercent: Option[Double] = None,
  /* Основное вознаграждение */
  sumBasicRewardAmount: Option[Double] = None,
  /* Колво пакетов Комфорт лайт */
  sumComfortLiteQuantity: Option[Int] = None,
  /* Сумма за пакет Комфорт лайт  */
  maxCLAmount: Option[Double] = None,
  /* Комфорт-Лайт */
  sumComfortLiteRewAmount: Option[Double] = None,
  /* Общая сумма за продажу всех услуг сгруппированных по ФПН кредитного продукта */
  groupSumAddService: Option[Double] = None,
  /* Сумма вознаграждения для кредитов с учетом страховки 00 */
  sumTotalRewardAmountGr0: Option[Double] = None,
  /* Сумма вознаграждения для кредитов без учета страховки 00 */
  sumTotalRewardAmountEq0: Option[Double] = None,
  /* Группировка дополнительных услуг */
  groupAddService: Option[Seq[RewardGroupAddService]] = None
) extends ApiModel


