/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class RewardCredits (
  lineNum: Option[String] = None,
  /* Регион */
  regionCentr: Option[String] = None,
  /* ФИО консультанта */
  consulter: Option[String] = None,
  /* ФИО заемщика */
  client: Option[String] = None,
  /* Номер кредит. договора */
  numberDoc: Option[String] = None,
  /* Фпн продукта */
  productFPN: Option[String] = None,
  /* Продукт */
  product: Option[String] = None,
  /* Группа кредитного продукта */
  productType: Option[String] = None,
  /* Группа продукта */
  prodGroup: Option[String] = None,
  /* Дата выдачи */
  issueDate: Option[Double] = None,
  /* Общая сумма */
  totalAmount: Option[Double] = None,
  /* Сумма на товар */
  goodsAmount: Option[Double] = None,
  /* Количество страховок */
  insurances: Option[Int] = None,
  /* Страхование жизни */
  lifeInsAmount: Option[Double] = None,
  /* Потеря работы */
  workInsAmount: Option[Double] = None,
  /* Признак продажи СП */
  iscl: Option[Boolean] = None,
  /* Комфорт-Лайт */
  rewCLAmount: Option[Double] = None,
  /* Вознаграждение баз */
  rewPercent: Option[Double] = None,
  /* Вознаграждение изм */
  rewPercent2: Option[Double] = None,
  /* Сумма вознаграждения */
  rewAmount: Option[Double] = None,
  /* Основное вознаграждение */
  basicRewardAmount: Option[Double] = None,
  /* Колво пакетов Комфорт лайт */
  comfortLiteQuantity: Option[Int] = None,
  /* Дивизион */
  division: Option[String] = None,
  /* Наименование торговой точки */
  merchantName: Option[String] = None,
  /* Кредитный продукт присутствует в схеме КВ */
  productInSchemeKV: Option[String] = None,
  /* Дополнительные услуги */
  rewADDS: Option[Seq[RewardRewADDS]] = None,
  ttguid: Option[String] = None,
  /* Код ТТ */
  ttCode: Option[String] = None,
  /* Код категории ТТ  */
  ttCategory: Option[String] = None,
  /* Сумма за пакет Комфорт лайт  */
  clAmount: Option[Double] = None,
  /* Итоговая сумма вознаграждения за Дополнительные услуги */
  addsRewardTotal: Option[Double] = None
) extends ApiModel


