/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class RewardRewADDS (
  /* Код дополнительной услуги */
  addsCode: Option[String] = None,
  /* Наименование дополнительной услуги */
  addsName: Option[String] = None,
  /* Сумма вознаграждения за продажу дополнительной услуги */
  addsRewardOne: Option[Double] = None,
  /* Количество проданных услуг */
  addsAmount: Option[Int] = None,
  /* Размер вознаграждения за продажу одной дополнительной услуги */
  addsRate: Option[Double] = None
) extends ApiModel


