/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class TradingPointTtCreditProduct (
  productGUID: Option[String] = None,
  fpn: Option[String] = None,
  product: Option[String] = None,
  dateOn: Option[Double] = None,
  dateOff: Option[Double] = None,
  code: Option[String] = None,
  agreementRole: Option[TradingPointAgreementRole] = None,
  ttDiscount: Option[Double] = None
) extends ApiModel


