/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class TradingPointPurpose (
  /* Отображаемое значение */
  name: Option[String] = None,
  /* Техническое поле */
  enumType: Option[String] = None,
  /* Отображаемое значение */
  description: Option[String] = None,
  /* pulledFiles - забрал досье, connectedAgent - подключил агента, heldTalks - провел переговоры по подключению новых кредитных продуктов, trainedEmployees - провел обучение сотрудников, postedPOSM - разместил POSM, reanimation - реанимация, specTask - спецзадача. Возможные значения  \"pulledFiles\", \"connectedAgent\", \"heldTalks\", \"trainedEmployees\", \"postedPOSM\", \"reanimation\", \"specTask\" */
  value: Option[String] = None
) extends ApiModel


