/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class TradingPointPurpose (
  content: Option[String] = None,
  code: Option[String] = None,
  value: Option[TradingPointPurposeEnums.Value] = None
) extends ApiModel

object TradingPointPurposeEnums {

  type Value = Value.Value
  object Value extends Enumeration {
    val PulledFiles = Value("pulledFiles")
    val ConnectedAgent = Value("connectedAgent")
    val HeldTalks = Value("heldTalks")
    val TrainedEmployees = Value("trainedEmployees")
    val PostedPOSM = Value("postedPOSM")
    val Reanimation = Value("reanimation")
    val SpecTask = Value("specTask")
  }

}

