/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class TradingPointTtBrokerHistory (
  guid: Option[String] = None,
  name: Option[String] = None,
  inn: Option[String] = None,
  authorOn: Option[String] = None,
  dateOn: Option[Double] = None,
  authorOff: Option[String] = None,
  dateOff: Option[Double] = None,
  ttDateOn: Option[Double] = None,
  ttDateOff: Option[Double] = None
) extends ApiModel


