/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class UserTmState (
  content: Option[String] = None,
  code: Option[String] = None,
  /* New - Новый, Active - Активный ТМ, NotWork - Не действует */
  value: Option[UserTmStateEnums.Value] = None
) extends ApiModel

object UserTmStateEnums {

  type Value = Value.Value
  object Value extends Enumeration {
    val `New` = Value("New")
    val Active = Value("Active")
    val NotWork = Value("NotWork")
  }

}

