/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class User (
  isBlocked: Option[Boolean] = None,
  description: Option[String] = None,
  login: Option[String] = None,
  userInfoID: Option[Int] = None,
  typeUser: Option[String] = None,
  phone: Option[String] = None,
  inn: Option[String] = None,
  guidDoc: Option[String] = None,
  isAllRegion: Option[Boolean] = None,
  roleName: Option[String] = None,
  roleSysName: Option[String] = None,
  sysOrgName: Option[String] = None,
  sysOrgSystemName: Option[String] = None,
  guidAgentPartner: Option[String] = None,
  agentID: Option[String] = None,
  fiorp: Option[String] = None,
  post: Option[String] = None,
  postRP: Option[String] = None,
  passportSeries: Option[String] = None,
  passportNumber: Option[String] = None,
  phonePEP: Option[String] = None,
  signerBank: Option[Boolean] = None,
  dateSendSMS: Option[Double] = None,
  userdocs: Option[Seq[UserUserdocs]] = None,
  cState: Option[String] = None,
  cStateDate: Option[Double] = None,
  fioLastname: Option[String] = None,
  fioFirstname: Option[String] = None,
  fioMiddleName: Option[String] = None,
  eMail: Option[String] = None,
  eMailUpper: Option[String] = None,
  tmAttribute: Option[Boolean] = None,
  tmState: Option[UserTmState] = None,
  tmStateDate: Option[Double] = None,
  tmRegion: Option[String] = None,
  tmDivision: Option[String] = None,
  tmPhantom: Option[Boolean] = None,
  tmPost: Option[String] = None,
  tmPostRP: Option[String] = None,
  tmSubdivision: Option[String] = None,
  tmTabnumber: Option[String] = None,
  tmType: Option[UserTmType] = None,
  fioUpperLastnameUpper: Option[String] = None,
  fioUpperFirstnameUpper: Option[String] = None,
  fioUpperMiddleNameUpper: Option[String] = None
) extends ApiModel


