/**
 * rest сервисы ренессанс
 * rest сервисы ренессанс
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class UserDetails (
  /* логин текущего пользователя */
  userName: String,
  /* фио текущего пользователя */
  fullUserName: String,
  /* роли пользователя */
  roles: Seq[String],
  /* адрес электронной почты текущего пользователя */
  email: String
) extends ApiModel


